/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package automation.rest.asure;

import io.restassured.RestAssured;
import io.restassured.http.ContentType;
import org.apache.http.HttpStatus;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;

import static io.restassured.RestAssured.given;
import static io.restassured.RestAssured.when;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.CoreMatchers.notNullValue;
import static org.junit.Assert.*;

public class AppTest {

    @BeforeClass
    public static void setup() {
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
    }
    @Test public void testeListMetadadosDoUsuario() {
        when().
                get("https://reqres.in/api/users?page=2").
        then().
            statusCode(HttpStatus.SC_OK).
            body("page", is(2)).
            body("data", is(notNullValue()));
    }

    @Test
    public void testeCriarUsuarioComSucesso(){
        given().
                contentType(ContentType.JSON).
                body("{\n" + " \"name\": \"larissa\",\n" + " \"job\": \"eng test\"\n" + "}").
        when().
            post("https://reqres.in/api/users").
        then().
            statusCode(HttpStatus.SC_CREATED).
            body("name", is( "larissa"));
    }
}
